config/routes.rb
Rails.application.routes.draw do
  get 'returns/new'
  get 'returns/create'
  get 'personal_information', to: 'personal_information#show', as: 'personal_information'
  devise_for :users, controllers: { registrations: 'registrations' }
  #define about page ----HITHAM
  #get '/about', to: 'pages#about', as: 'about'
  #get '/contact', to: 'pages#contact', as: 'contact'
# get cat
  root 'store#cat'
  get 'store/cat', to: 'store#cat', as: 'home'
#  get 'personal_information/show'
delete '/users/:id', to: 'users#destroy', as: 'delete_user'
get 'account_deletion/confirm', to: 'account_deletion#confirm', as: 'confirm_account_deletion'
delete 'confirm_account_deletion', to: 'personal_information#destroy', as: 'delete_personal_information'




  get 'items', to: 'items#index', as: 'items'
  get 'items/:id', to: 'items#show', as: 'item'
  get 'checkout/index'
  #devise_for :users

  # STO-7
  get 'products', to: 'products#index', as: 'products'
  post 'products', to: 'products#create'
  get 'product/new', to: 'products#new', as: 'product_new'
  get "product/:id", to: 'products#show', as: 'product'
  get "product/:id/edit", to: 'products#edit', as: 'product_edit'
  patch 'product/:id', to: 'products#update'
  delete 'product/:id', to: 'products#destroy'
  # end of STO-7

  # STO-6
  get 'orders/', to: 'orders#index', as: 'orders'
  post 'orders/:id', to: 'orders#create'
  get 'orders/:id', to: 'orders#show', as: 'order'

  post 'orders', to: 'orders#create_from_cart', as: 'create_from_carts'
  # end of STO-6

  # STO-Review
  post 'items/:product_id/reviews', to: 'reviews#create', as: 'reviews'
  get 'items/:product_id/reviews/new', to: 'reviews#new', as: 'review_new'
  get 'items/:product_id/reviews/:id/edit', to: 'reviews#edit', as: 'review_edit'
  patch 'items/:product_id/reviews/:id', to: 'reviews#update', as: 'review'
  delete 'items/:product_id/reviews/:id', to: 'reviews#destroy', as: 'review_destroy'

  #get 'products', to: 'products#index', as: 'products'
  get 'carts', to: 'carts#index', as: 'carts'
  get 'wishlists', to: 'wishlists#index', as: 'wishlists'
  post 'carts', to: 'carts#add_to_cart', as: 'add_to_cart'
  get '/checkout', to: 'checkout#index', as: 'checkout'
  patch 'update_quantity_cart/:id', to: 'carts#update_quantity', as: 'update_quantity_cart'
  get 'wishlists/:id/edit', to: 'wishlists#edit', as: 'edit_wishlist_item'
  post 'carts', to: 'carts#dd_to_cart'
  #get 'wishlists/:id/add_to_cart', to: 'wishlists#add_to_cart'
  delete 'carts/:id', to: 'carts#destroy'
  delete 'wishlists/:id', to: 'wishlists#destroy'
  get 'carts/:id/edit', to: 'carts#edit', as: 'edit_cart'
  patch 'wishlists/:id', to: 'wishlists#update'
  patch 'carts/:id', to: 'carts#update'
 # patch 'carts/:id', to: 'carts#update'
  resources :carts
  resources :wishlists

  resources :carts, only: [:index, :show, :edit, :update, :destroy]

  # STO-Review
  # resources :products do
    # resources :reviews, only: [:new, :create]
  # end

  resources :carts do
    member do
      delete 'destroy'
    end
  end

  resources :wishlists, only: [:index, :show, :edit, :update, :destroy]
  resources :wishlists do
    post 'add_to_cart', on: :member
  end
  resources :carts, only: [:edit, :update]

  resources :wishlists do
    member do

      delete :remove_from_wishlist
      put :update_quantity

    end
  end

  resources :products do
    resources :wishlist_item
  end
  resources :wishlists do
    member do
      post 'add_to_cart'
    end
  end
  resources :carts do
    patch 'update_quantity', on: :member
  end
  resources :carts do
    member do
      delete 'remove_from_cart'
    end
  end
  resources :carts do
    patch :update_quantity, on: :member
  end
  resources :carts do
    post 'checkout_from_cart', on: :member
  end
  # config/routes.rb

resources :carts do
  patch :update, on: :member
end
resources :orders do
  post 'checkout_from_carts', on: :collection
end
# config/routes.rb

resources :orders, only: [:new, :create, :show]
resources :products, only: [:show]

  # Defines the root path route ("/")
  # root "articles#index"
  resources :products, only: [:show]
# config/routes.rb


  resources :orders do
    resource :return, only: [:new, :create]
  end
end

app/views/shared/_flash.html.erb
<% flash.each do |key, message| %>
  <div class="alert <%= alert_class(key) %> alert-dismissible fade show" role="alert">
    <div class="text-center alert-message"><%= message %></div>
    <button type="button" class="btn-close" data-bs-dismiss="alert" aria-label="Close"></button>
  </div>
<% end %>

app/views/shared/_navbar.html.erb
<!DOCTYPE html>
<html lang="en">
<head>
  <meta charset="UTF-8">
  <meta name="viewport" content="width=device-width, initial-scale=1.0">
  <link rel="stylesheet" href="https://cdn.jsdelivr.net/npm/bootstrap@5.3.0/dist/css/bootstrap.min.css">
  <style>
    body {
      font-family: 'Arial', sans-serif;
      background-color: #fff; 
      color: #000; 
      margin: 0;
      padding: 0;
    }
    .navbar {
      background-color: #fff; 
      box-shadow: 0 4px 6px rgba(0, 0, 0, 0.1);
    }
    .navbar-toggler {
      border-color: #fff;
      background-color: transparent !important;
    }
    .navbar-toggler-icon {
      background-color: #fff;
    }
    .navbar-nav {
      margin-left: auto;
    }
    .navbar-nav .profile-link {
      color: #000;
      margin: 0 10px;
      padding: 10px 15px;
      border-radius: 5px;
      transition: background-color 0.3s ease;
       display: block;
    }
    .navbar-nav .profile-link:hover {
      background-color: #555;
    }

    .navbar-brand {
      font-family: 'Georgia', serif;
      font-size: 24px;
      color: #000;
    }
  </style>
  <title></title>
</head>
<body>

<nav class="navbar navbar-light">
  <div class="container">
    <button class="navbar-toggler" type="button" data-bs-toggle="collapse" data-bs-target="#navbarNavDropdown" aria-controls="navbarNavDropdown" aria-expanded="false" aria-label="Toggle navigation">
      <span class="navbar-toggler-icon"></span>
    </button>

<% if user_signed_in? %>
  <div class="d-flex align-items-center ml-auto">
    <%= button_to 'Sign Out', destroy_user_session_path, method: :delete, data: { turbo: false }, class: 'btn btn-link text-center', style: "color: #ff9999;" %>
    <%= link_to personal_information_path(current_user) do %>
      <svg xmlns="http://www.w3.org/2000/svg" width="30" height="30" fill="currentColor" class="bi bi-person-circle me-2" viewBox="0 0 16 16" style="color: gray;">
        <path d="M11 6a3 3 0 1 1-6 0 3 3 0 0 1 6 0"/>
        <path fill-rule="evenodd" d="M0 8a8 8 0 1 1 16 0A8 8 0 0 1 0 8m8-7a7 7 0 0 0-5.468 11.37C3.242 11.226 4.805 10 8 10s4.757 1.225 5.468 2.37A7 7 0 0 0 8 1"/>
      </svg>
    <% end %>
  </div>
<% end %>

    <div class="collapse navbar-collapse" id="navbarNavDropdown">
      <ul class="navbar-nav">
        <li class="nav-item">
          <a class="nav-link active" aria-current="page" href="<%= home_path %>">Home</a>
          <a class="nav-link" href="<%= items_path %>">Shop</a>
          <a class="nav-link" href="<%= wishlists_path %>">Wishlist</a>
          <a class="nav-link" href="<%= carts_path %>">Cart</a>
          <a class="nav-link" href="<%= orders_path %>">Orders</a>
          <% if user_signed_in? %>
            <% if current_user.admin? %>
              <a class="nav-link" href="<%= products_path %>">Your Products</a>
            <% end %>
          <% end %>
        </li>
      </ul>
    </div>
  </div>
</nav>


</body>
</html>

         
   
    