config/routes.rb
Rails.application.routes.draw do
  get 'returns/new'
  get 'returns/create'
  get 'personal_information', to: 'personal_information#show', as: 'personal_information'
  devise_for :users, controllers: { registrations: 'registrations' }
  #define about page ----HITHAM
  #get '/about', to: 'pages#about', as: 'about'
  #get '/contact', to: 'pages#contact', as: 'contact'
# get cat
  root 'store#cat'
  get 'store/cat', to: 'store#cat', as: 'home'
#  get 'personal_information/show'
delete '/users/:id', to: 'users#destroy', as: 'delete_user'
get 'account_deletion/confirm', to: 'account_deletion#confirm', as: 'confirm_account_deletion'
delete 'confirm_account_deletion', to: 'personal_information#destroy', as: 'delete_personal_information'




  get 'items', to: 'items#index', as: 'items'
  get 'items/:id', to: 'items#show', as: 'item'
  get 'checkout/index'
  #devise_for :users

  # STO-7
  get 'products', to: 'products#index', as: 'products'
  post 'products', to: 'products#create'
  get 'product/new', to: 'products#new', as: 'product_new'
  get "product/:id", to: 'products#show', as: 'product'
  get "product/:id/edit", to: 'products#edit', as: 'product_edit'
  patch 'product/:id', to: 'products#update'
  delete 'product/:id', to: 'products#destroy'
  # end of STO-7

  # STO-6
  get 'orders/', to: 'orders#index', as: 'orders'
  post 'orders/:id', to: 'orders#create'
  get 'orders/:id', to: 'orders#show', as: 'order'

  post 'orders', to: 'orders#create_from_cart', as: 'create_from_carts'
  # end of STO-6

  # STO-Review
  post 'items/:product_id/reviews', to: 'reviews#create', as: 'reviews'
  get 'items/:product_id/reviews/new', to: 'reviews#new', as: 'review_new'
  get 'items/:product_id/reviews/:id/edit', to: 'reviews#edit', as: 'review_edit'
  patch 'items/:product_id/reviews/:id', to: 'reviews#update', as: 'review'
  delete 'items/:product_id/reviews/:id', to: 'reviews#destroy', as: 'review_destroy'

  #get 'products', to: 'products#index', as: 'products'
  get 'carts', to: 'carts#index', as: 'carts'
  get 'wishlists', to: 'wishlists#index', as: 'wishlists'
  post 'carts', to: 'carts#add_to_cart', as: 'add_to_cart'
  get '/checkout', to: 'checkout#index', as: 'checkout'
  patch 'update_quantity_cart/:id', to: 'carts#update_quantity', as: 'update_quantity_cart'
  get 'wishlists/:id/edit', to: 'wishlists#edit', as: 'edit_wishlist_item'
  post 'carts', to: 'carts#dd_to_cart'
  #get 'wishlists/:id/add_to_cart', to: 'wishlists#add_to_cart'
  delete 'carts/:id', to: 'carts#destroy'
  delete 'wishlists/:id', to: 'wishlists#destroy'
  get 'carts/:id/edit', to: 'carts#edit', as: 'edit_cart'
  patch 'wishlists/:id', to: 'wishlists#update'
  patch 'carts/:id', to: 'carts#update'
 # patch 'carts/:id', to: 'carts#update'
  resources :carts
  resources :wishlists

  resources :carts, only: [:index, :show, :edit, :update, :destroy]

  # STO-Review
  # resources :products do
    # resources :reviews, only: [:new, :create]
  # end

  resources :carts do
    member do
      delete 'destroy'
    end
  end

  resources :wishlists, only: [:index, :show, :edit, :update, :destroy]
  resources :wishlists do
    post 'add_to_cart', on: :member
  end
  resources :carts, only: [:edit, :update]

  resources :wishlists do
    member do

      delete :remove_from_wishlist
      put :update_quantity

    end
  end

  resources :products do
    resources :wishlist_item
  end
  resources :wishlists do
    member do
      post 'add_to_cart'
    end
  end
  resources :carts do
    patch 'update_quantity', on: :member
  end
  resources :carts do
    member do
      delete 'remove_from_cart'
    end
  end
  resources :carts do
    patch :update_quantity, on: :member
  end
  resources :carts do
    post 'checkout_from_cart', on: :member
  end
  # config/routes.rb

resources :carts do
  patch :update, on: :member
end
resources :orders do
  post 'checkout_from_carts', on: :collection
end
# config/routes.rb

resources :orders, only: [:new, :create, :show]
resources :products, only: [:show]

  # Defines the root path route ("/")
  # root "articles#index"
  resources :products, only: [:show]
# config/routes.rb


  resources :orders do
    resource :return, only: [:new, :create]
  end
end

app/models/cart.rb
# == Schema Information
#
# Table name: carts
#
#  id         :bigint           not null, primary key
#  quantity   :integer
#  created_at :datetime         not null
#  updated_at :datetime         not null
#  product_id :bigint           not null
#  user_id    :bigint
#
# Indexes
#
#  index_carts_on_product_id  (product_id)
#  index_carts_on_user_id     (user_id)
#
# Foreign Keys
#
#  fk_rails_...  (product_id => products.id)
#  fk_rails_...  (user_id => users.id)
#
class Cart < ApplicationRecord
  belongs_to :product
  validates :quantity, presence: true, numericality: { greater_than: 0 }
  validates :product_id, presence: true
  def subtotal
    quantity * product.price
  end
end

app/controllers/carts_controller.rb
# app/controllers/carts_controller.rb

class CartsController < ApplicationController
  before_action :find_cart_item, only: [:show, :edit, :update_quantity, :destroy, :checkout_from_cart]
  before_action :authenticate_user!


  def index
    @carts = Cart.includes(product: :user).all
    @cart = Cart.new
  end

  def show
    # @cart_item is set by the before_action
  end

  def add_to_cart
    existing_cart_item = Cart.find_by(product_id: cart_params[:product_id], user_id: current_user.id)

    if existing_cart_item
      existing_cart_item.quantity += cart_params[:quantity].to_i
      if existing_cart_item.save
        flash[:success] = 'Cart item quantity updated successfully!'
      else
        flash[:error] = 'Failed to update cart item quantity'
      end
    else
      @cart = Cart.new(cart_params)
      @cart.user_id = current_user.id  # Set the user_id for the cart
      if @cart.save
        flash[:success] = 'New product successfully added to cart'
      else
        flash[:error] = 'Product adding failed'
      end
    end

    redirect_to carts_url
  end



  def edit
    # @cart_item is set by the before_action
  end

  def update_quantity
    if @cart_item.update(cart_params)
      flash[:success] = 'Cart item quantity updated successfully!'
      redirect_to carts_path
    else
      flash.now[:error] = 'Failed to update cart item quantity'
      render :edit, status: :unprocessable_entity
    end
  end
  def destroy
    @cart = Cart.find_by(id: params[:id])

    if @cart
      @cart.destroy
      flash[:success] = 'The cart item was successfully removed'
    else
      flash[:error] = 'Cart item not found or does not exist.'
    end

    redirect_to carts_url, status: :see_other
  end

  private

  def find_cart_item
    @cart_item = Cart.find_by(id: params[:id])

    if @cart_item.nil?
      flash[:error] = 'Cart item not found or does not exist.'
      redirect_to carts_path and return
    end
  end

  def cart_params
    params.require(:cart).permit(:quantity, :product_id)
  end


end

app/helpers/carts_helper.rb
module CartsHelper
end

app/views/carts/destroy,html.erb
<%= form_for @cart, url: cart_path(@cart), method: :delete do |f| %>
  <% if @cart.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(@cart.errors.count, 'error') %> prohibited this cart from being deleted:</h2>
      <ul>
        <% @cart.errors.full_messages.each do |message| %>
          <li><%= message %></li>
        <% end %>
      </ul>
    </div>
  <% end %>

  <%= f.submit 'Delete' %>
<% end %>

app/views/carts/edit.html.erb
<!-- app/views/carts/edit.html.erb -->

<h1>Edit Cart Item</h1>

<%= bootstrap_form_with(model: @cart_item, url: cart_path(@cart_item), method: :patch, local: true) do |form| %>

  <%= form.hidden_field :product_id, value: @cart_item.product.id %>

  <div class="field">
    <%= form.label :quantity %>
    <%= form.number_field :quantity %>
    <% if @cart_item.errors.has_key?(:quantity) %>
      <p class="text-danger"><%= @cart_item.errors.full_messages_for(:quantity).first %></p>
    <% end %>
  </div>

  <!-- Add other form fields for CartItem attributes -->
  <!-- Repeat the above pattern for other attributes -->

  <div class="actions">
    <%= form.submit 'Update Cart Item' %>
  </div>

  <% if @cart_item.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(@cart_item.errors.count, 'error') %> prohibited this cart item from being updated:</h2>
      <ul>
        <% @cart_item.errors.full_messages.each do |message| %>
          <li><%= message %></li>
        <% end %>
      </ul>
    </div>
  <% end %>
<% end %>

app/views/carts/index.html.erb
<!-- app/views/carts/index.html.erb -->

<h1>Your Shopping Cart</h1>

<% if @carts.empty? %>
  <p>No items in your cart.</p>
<% else %>
  <table class="table table-hover">
    <thead>
      <tr>
        <th>Product</th>
        <th>Quantity</th>
        <th>Price</th>
        <th>Total</th>
        <th>Action</th>
      </tr>
    </thead>
    <tbody>
      <% @carts.each do |cart_item| %>
        <% product = cart_item.product %>
        <% next unless product %>
        <tr>
          <td><%= product.name %></td>
          <td>
            <%= form_with(model: cart_item, url: update_quantity_cart_path(cart_item), method: :patch, local: true) do |form| %>
              <%= form.number_field :quantity, class: 'form-control', min: 1 %>
              <% if cart_item.errors.has_key?(:quantity) %>
                <p class="text-danger"><%= cart_item.errors.full_messages_for(:quantity).first %></p>
              <% end %>
              <%= form.submit 'Update', class: 'btn btn-primary update-quantity-btn' %>
            <% end %>
          </td>
          <td><%= number_to_currency(product.price) %></td>
          <td><%= number_to_currency(cart_item.quantity * product.price) %></td>
          <td>
            <%= button_to "Delete", cart_path(cart_item), method: :delete, data: { turbo: false }, class: "btn btn-sm btn-danger" %>
          </td>
        </tr>
      <% end %>
    </tbody>
  </table>

  <% if @cart.present? %>
    <%= link_to 'Checkout', checkout_path, class: 'btn btn-success checkout-btn' %>
  <% end %>
<% end %>

app/views/carts/show.html.erb
<!-- app/views/carts/show.html.erb -->

<h1>Cart Item Details</h1>

<% if @cart_item.errors.any? %>
  <div id="error_explanation">
    <h2><%= pluralize(@cart_item.errors.count, 'error') %> prohibited this cart item from being saved:</h2>
    <ul>
      <% @cart_item.errors.full_messages.each do |message| %>
        <li><%= message %></li>
      <% end %>
    </ul>
  </div>
<% end %>

<table class="table table-hover">
  <thead>
    <tr>
      <th>Product</th>
      <th>Quantity</th>
      <th>Price</th>
      <th>Total</th>
      <!-- Add other columns as needed -->
    </tr>
  </thead>
  <tbody>
    <tr>
      <td><%= @cart_item.product.name %></td>
      <td><%= @cart_item.quantity %></td>
      <td><%= number_to_currency(@cart_item.product.price) %></td>
      <td><%= number_to_currency(@cart_item.quantity * @cart_item.product.price) %></td>
      <!-- Add other cells as needed -->
    </tr>
  </tbody>
</table>

<%= link_to 'Back to Cart', carts_path, class: 'btn btn-primary' %>