config/routes.rb
Rails.application.routes.draw do
  get 'returns/new'
  get 'returns/create'
  get 'personal_information', to: 'personal_information#show', as: 'personal_information'
  devise_for :users, controllers: { registrations: 'registrations' }
  #define about page ----HITHAM
  #get '/about', to: 'pages#about', as: 'about'
  #get '/contact', to: 'pages#contact', as: 'contact'
# get cat
  root 'store#cat'
  get 'store/cat', to: 'store#cat', as: 'home'
#  get 'personal_information/show'
delete '/users/:id', to: 'users#destroy', as: 'delete_user'
get 'account_deletion/confirm', to: 'account_deletion#confirm', as: 'confirm_account_deletion'
delete 'confirm_account_deletion', to: 'personal_information#destroy', as: 'delete_personal_information'




  get 'items', to: 'items#index', as: 'items'
  get 'items/:id', to: 'items#show', as: 'item'
  get 'checkout/index'
  #devise_for :users

  # STO-7
  get 'products', to: 'products#index', as: 'products'
  post 'products', to: 'products#create'
  get 'product/new', to: 'products#new', as: 'product_new'
  get "product/:id", to: 'products#show', as: 'product'
  get "product/:id/edit", to: 'products#edit', as: 'product_edit'
  patch 'product/:id', to: 'products#update'
  delete 'product/:id', to: 'products#destroy'
  # end of STO-7

  # STO-6
  get 'orders/', to: 'orders#index', as: 'orders'
  post 'orders/:id', to: 'orders#create'
  get 'orders/:id', to: 'orders#show', as: 'order'

  post 'orders', to: 'orders#create_from_cart', as: 'create_from_carts'
  # end of STO-6

  # STO-Review
  post 'items/:product_id/reviews', to: 'reviews#create', as: 'reviews'
  get 'items/:product_id/reviews/new', to: 'reviews#new', as: 'review_new'
  get 'items/:product_id/reviews/:id/edit', to: 'reviews#edit', as: 'review_edit'
  patch 'items/:product_id/reviews/:id', to: 'reviews#update', as: 'review'
  delete 'items/:product_id/reviews/:id', to: 'reviews#destroy', as: 'review_destroy'

  #get 'products', to: 'products#index', as: 'products'
  get 'carts', to: 'carts#index', as: 'carts'
  get 'wishlists', to: 'wishlists#index', as: 'wishlists'
  post 'carts', to: 'carts#add_to_cart', as: 'add_to_cart'
  get '/checkout', to: 'checkout#index', as: 'checkout'
  patch 'update_quantity_cart/:id', to: 'carts#update_quantity', as: 'update_quantity_cart'
  get 'wishlists/:id/edit', to: 'wishlists#edit', as: 'edit_wishlist_item'
  post 'carts', to: 'carts#dd_to_cart'
  #get 'wishlists/:id/add_to_cart', to: 'wishlists#add_to_cart'
  delete 'carts/:id', to: 'carts#destroy'
  delete 'wishlists/:id', to: 'wishlists#destroy'
  get 'carts/:id/edit', to: 'carts#edit', as: 'edit_cart'
  patch 'wishlists/:id', to: 'wishlists#update'
  patch 'carts/:id', to: 'carts#update'
 # patch 'carts/:id', to: 'carts#update'
  resources :carts
  resources :wishlists

  resources :carts, only: [:index, :show, :edit, :update, :destroy]

  # STO-Review
  # resources :products do
    # resources :reviews, only: [:new, :create]
  # end

  resources :carts do
    member do
      delete 'destroy'
    end
  end

  resources :wishlists, only: [:index, :show, :edit, :update, :destroy]
  resources :wishlists do
    post 'add_to_cart', on: :member
  end
  resources :carts, only: [:edit, :update]

  resources :wishlists do
    member do

      delete :remove_from_wishlist
      put :update_quantity

    end
  end

  resources :products do
    resources :wishlist_item
  end
  resources :wishlists do
    member do
      post 'add_to_cart'
    end
  end
  resources :carts do
    patch 'update_quantity', on: :member
  end
  resources :carts do
    member do
      delete 'remove_from_cart'
    end
  end
  resources :carts do
    patch :update_quantity, on: :member
  end
  resources :carts do
    post 'checkout_from_cart', on: :member
  end
  # config/routes.rb

resources :carts do
  patch :update, on: :member
end
resources :orders do
  post 'checkout_from_carts', on: :collection
end
# config/routes.rb

resources :orders, only: [:new, :create, :show]
resources :products, only: [:show]

  # Defines the root path route ("/")
  # root "articles#index"
  resources :products, only: [:show]
# config/routes.rb


  resources :orders do
    resource :return, only: [:new, :create]
  end
end

app/models/product.rb
# == Schema Information
#
# Table name: products
#
#  id          :bigint           not null, primary key
#  available   :boolean          default(TRUE)
#  category    :string
#  description :string
#  image       :string
#  name        :string
#  price       :decimal(, )
#  user        :string
#  created_at  :datetime         not null
#  updated_at  :datetime         not null
#  user_id     :bigint
#
# Indexes
#
#  index_products_on_user_id  (user_id)
#
# Foreign Keys
#
#  fk_rails_...  (user_id => users.id)
#
class Product < ApplicationRecord
  # STO-7
  belongs_to(
    :user,
    class_name: 'User',
    foreign_key: 'user_id',
    inverse_of: :products,
  )

  # Active Storage
  has_one_attached :image

  # STO-6_9
  has_many(
    :histories,
    class_name: "History",
    foreign_key: "product_id",
    inverse_of: :product,
    dependent: :destroy
  )

  has_many :orders, through: :histories

  # STO-Review
  has_many(
    :review,
    class_name: "Review",
    foreign_key: "product_id",
    inverse_of: :product,
    dependent: :destroy
  )

  # STO-Review Update
  has_many(
    :reviewables,
    class_name: "Reviewable",
    foreign_key: "product_id",
    inverse_of: :product,
    dependent: :destroy
  )

  def average_rating
    review.average(:rating).to_f.round(1)
  end
end

app/controllers/products_controller.rb
class ProductsController < ApplicationController
  before_action :authenticate_user!, except: [:index]
  before_action :creator_permission, except: [:index, :show, :new, :create]
  before_action :isAdmin

  def isAdmin
    if current_user.admin == false
      flash[:error] = 'You are not an admin'
      redirect_to items_url
    end
  end

  def creator_permission 
    @product = Product.find(params[:id])
    if current_user.admin == false
      flash[:error] = 'You are not an admin'
      redirect_to products_url
    else
      unless current_user == @product.user
        flash[:error] = 'You do not have permission to do that.'
        redirect_to products_url
      end
    end
  end

  def product_params
    params.require(:product).permit(:name, :description, :category, :price, :image)
  end
  
  def index
      @products=Product.order(:name)
      render :index
  end

  def show
    @product=Product.find(params[:id])
    render :show
  end

  def new 
    @product = current_user.products.build
    render :new
  end

  def create
    @product = current_user.products.build(params.require(:product).permit(:name, :description, :category, :price, :image, :user, :available))

    if @product.save 
      flash['success'] = "#{@product.name} has been created!"
      redirect_to product_url(@product)
    else
      flash.now['error'] = 'Error! Unable to create product.'
      render :new, status: :unprocessable_entity
    end
  end

  def edit
    @product = current_user.products.find(params[:id])
    render :edit
  end 

  def update
    @product = current_user.products.find(params[:id])
    if @product.update(params.require(:product).permit(:name, :description, :category, :price, :image, :user, :available))
      flash['success'] = "#{@product.name} has been updated!"
      redirect_to product_url(@product)
    else
      flash.now['error'] = 'Error! Unable to update product.'
      render :edit, status: :unprocessable_entity
    end
  end

  def destroy
    @product = Product.find(params[:id])
    @product.destroy

    flash[:success] = "The item was successfully destroyed"
    redirect_to products_url, stats: :see_other
  end

end

app/helpers/products_helper.rb
module ProductsHelper
end

app/views/products/edit.html.erb
<h1> Edit Product: <%= @product.name %> </h1>

<%= bootstrap_form_with model: @product, method: :patch, url: product_path(@product), data: { turbo: false } do |f| %>
  <%= f.text_field :name %>
  <%= f.text_area :description %>
  <%= f.text_field :category %>
  <%= f.number_field :price %>
  <%= f.file_field :image %>
  <%= f.check_box :available %>
  <%= f.submit%>
<% end %>

app/views/products/index.html.erb
<!DOCTYPE html>
<html lang="en">
<head>
  <meta charset="UTF-8">
  <meta name="viewport" content="width=device-width, initial-scale=1.0">

  <link rel="stylesheet" href="https://cdn.jsdelivr.net/npm/bootstrap@5.3.0/dist/css/bootstrap.min.css">
  <style>
    body {
      font-family: 'Arial', sans-serif;
      background-color: #fff; 
      color: #000; 
      margin: 0;
      padding: 0;
    }

    h1 {
      color: #007bff;
      margin-bottom: 20px;
    }

    .filter-options {
      margin-bottom: 20px;
    }

    .filter-options a.btn-primary,
    .filter-options a.btn-secondary {
      background-color: #007bff; 
      border-color: #007bff;
      color: #fff;
      margin-right: 10px;
    }

    .filter-options a.btn-primary:hover,
    .filter-options a.btn-secondary:hover {
      background-color: #0056b3; 
      border-color: #0056b3;
    }


   
    .row {
      margin: 0 -15px;
    }

    .col-md-4 {
      padding: 0 15px;
    }

    .card {
      width: 100%;
      height: 100%;
      cursor: pointer;
      transition: transform 0.3s ease-in-out;
    }

    .card:hover {
      transform: scale(1.05);
    }

    .card-img-top {
      height: 200px;
      width: 100%;
      object-fit: cover;
    }

    .card-body {
      padding: 10px;
    }

    .card-title {
      font-size: 18px;
      margin-bottom: 5px;
    }

    .card-text {
      color: #007bff; 
    }
     .orders-link {
      display: inline-block;
      padding: 10px 15px;
      background-color: #007bff;
      color: #fff;
      text-decoration: none;
      border-radius: 5px;
      transition: background-color 0.3s ease;
    }

    .orders-link:hover {
      background-color: #0056b3;
    }


  </style>
  <title>Your Page Title</title>
</head>
<body>

<h1>Your Products</h1>

<div class="filter-options mb-3">
  <%= link_to "Filter by Food", products_path(category: 'food', price: params[:price]), class: "btn btn-primary mr-2" %>
  <%= link_to "Filter by Toy", products_path(category: 'toy', price: params[:price]), class: "btn btn-primary mr-2" %>
  <%= link_to "Sort by Price (Low to High)", products_path(category: params[:category], price: 'asc'), class: "btn btn-primary mr-2" %>
  <%= link_to "Sort by Price (High to Low)", products_path(category: params[:category], price: 'desc'), class: "btn btn-primary mr-2" %>
  <%= link_to "Clear Filters", products_path, class: "btn btn-secondary" %>
</div>

<div class="row">
  <% if not current_user.products.exists? %>
    <h1>You Don't Have any Products, Create One!!!</h1>
  <% else %>
  <% @products.each do |product| %>
      <% if product.user == current_user %>
        <div class="col-md-4 mb-4">
          <div class="card" style="width: 300px; height: 375px; cursor: pointer;" onclick="window.location='<%= product_path(product) %>';">
              <% if product.image.attached? %>
                <%= image_tag product.image, class: "card-img-top", alt: product.name, style: "height: 300px; width: auto;" %>
              <% else %>
                <%= image_tag "default_img.jpeg", class: "card-img-top", alt: "Default Image", style: "height: 300px; width: auto;" %>
              <% end %>
            <div class="card-body">
              <h5 class="card-title"><%= product.name %></h5>
              <p class="card-text">Price: <%= number_to_currency(product.price, precision: 2) %></p>
            </div>
      <% end %>
        </div>
      </div>
    <% end %>
  <% end %>
</div>


<p><%= link_to "View Your Orders", orders_path,class: "orders-link"%></p>
<p><%= link_to "Create a Product", product_new_path,class: "orders-link"%></p>



app/views/products/new.html.erb
<h1> New Product </h1>

<%= bootstrap_form_with model: @product, method: :post, url: products_url, data: { turbo: false } do |f| %>
  <%= f.text_field :name %>
  <%= f.text_area :description %>
  <%= f.text_field :category %>
  <%= f.number_field :price, step: '0.01'%>
  <%= f.file_field :image %>
  <%= f.submit%>
<% end %>

app/views/products/show.html.erb
<div class="row">
  <div class="col-md-8">
    <div class="product-details">
      <h1><%= @product.name %></h1>

      <div class="description">
        <strong>Description:</strong>
        <p><%= @product.description %></p>
      </div>

      <div class="price">
        <strong>Price:</strong>
        <p><%= number_to_currency(@product.price) %></p>
      </div>

      <% if @product.image.present? %>
        <%= image_tag @product.image, class: "img-fluid", alt: @product.name %>
      <% end %>

      <div class="col-md-4 mt-md-auto text-md-end">
        <% if @product.user == current_user %>
          <p><%= link_to "Edit #{@product.name}?", product_edit_path(@product), class: "btn btn-secondary" %></p>
          <p><%= button_to "Destroy #{@product.name}?", product_path(@product), method: :delete, data: { turbo: false }, class: "btn btn-outline-secondary btn-danger", form: { class: "d-inline" } %></p>
        <% end %>
      </div>
        </div>
      </div>

      <div class="col-md-2 mt-md-auto text-md-start">
        <p><%= link_to 'Back to Products', products_url, class: 'btn btn-secondary' %></p>
      </div>
</div>

<h3> Reviews </h3>


<% if @product.review.present? %>
  <p> Average Rating: <%= @product.average_rating %> </p>
  <% @product.review.each do |review| %>
    <p> _________________________</p>
    <p> <%= review.user.full_name %> | Rated <%= review.rating %>/5 </p>
    <p> <%= review.text %> </p>
    <% if review.user == current_user %>
      <%= link_to 'Edit?', review_edit_path(review), class: 'btn btn-outline-secondary btn-secondary', form: { class: 'd-inline' } %>
      <%= button_to 'Destroy?', review_destroy_path(@product, review), method: :delete, data: { turbo: false }, class: 'btn btn-outline-secondary btn-warning', form: { class: 'd-inline' } %>
    <% end %>
  <% end %>
<% else %>
  <p>No reviews for this product.</p>
<% end %>
